import os

base_dir = os.path.dirname(os.path.realpath(__file__))


class BaseConfig(object):
    ENV = None
    Testing = False


class DevelopmentConfig(BaseConfig):
    # SQLALCHEMY_DATABASE_URI = "sqlite:///{path}/app.db".format(path=base_dir)
    # SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/flask_sampleapp_dev'
    SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://postgres:postgres@db:5432/flask_sampleapp_dev'  # docker
    SECRET_KEY = 'your secret key'


class StagingConfig(BaseConfig):
    ENV = 'staging'
    SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/flask_sampleapp_stg'
    SECRET_KEY = '\xbb\x94x #\xca\xc1\xa5\x9bX\x83`\xa7\tr\xe3'  # generated by "python -c 'import os; print(os.urandom(16))'"


class ProductionConfig(BaseConfig):
    ENV = 'production'
    SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/flask_sampleapp_prd'
    SECRET_KEY = 'C\x8bU\xceZ\xf9e\xef\xd4\xe5\xfb\xdbq\xe5h\x16'


class TestConfig(BaseConfig):
    ENV = 'test'
    TESTING = True
    # SQLALCHEMY_DATABASE_URI = "sqlite:///{path}/test.db".format(path=base_dir)
    SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://postgres:postgres@db:5432/flask_sampleapp_test'  # docker
    SECRET_KEY = 'your secret key'
