version: '2'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    # command: python manage.py runserver
    command: flask run --host 0.0.0.0
    # volumes:
    #   - .:/app
    links:
      - db
    environment:
      FLASK_ENV: development
      FLASK_APP: manage.py
  db:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
